name: ci first demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # step 1: checkout repository code
      - name: Checkout code from repository
        uses: actions/checkout@v4

      # step 2: set up python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # step 3: install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # step 4: run tests or demo command
      - name: Run the demo
        run: pytest
